### ISSUE TITLE
Allow multiple shops per instance

### ISSUE THREAD

**Issue by Narigo** [compose-us-research/noqueue#18]
**Description**
Right now, it's only possible to start up multiple docker containers and run them separately. A reverse proxy would be necessary to combine their URLs together into one. It should be possible for a single server to serve multiple shops.

**Links/References**
(Add any designs, screenshots or links that helpful to implement the feature)

**Tasks**

- [ ] Add a way to register a shop
  - [x] Use prefix or use database per shop? -> prefix
  - [x] Add prefix tables per shop
    - [x] Create Client for the global shop database (consisting of names/ids of shops)
    - [x] Create Client for the shop databases
  - [x] Loop through the middleware and set it up for each database
  - [ ] Duplicate `UpdateShop` screen for registering
- [ ] Add a global registry for all shops
  - [ ] Use the list screen to browse through all shops

**Additional Context**
(Add any additional context relevant to this feature)
