### ISSUE TITLE
Add labels for input fields

### ISSUE THREAD

**Issue by Narigo** [compose-us-research/noqueue#19]
**Description**
Screendesign for input fields is now done, we have a better way to handle labels now.

**Links/References**
![image](https://user-images.githubusercontent.com/1767865/83328246-e97d3800-a281-11ea-8913-5483f5f0b8d4.png)

**Tasks**

- [ ] Add placeholder field to input (text) fields
- [ ] Add label above the input field
- [ ] Fix all fields to have placeholder and labels

**Additional Context**
-
