### ISSUE TITLE
Complete server setup

### ISSUE THREAD

**Issue by Narigo** [compose-us-research/noqueue#23]
**Description**
Right now the webserver listens on port 8080. This should not be exposed to the outside world - instead, HTTPS should be served and the Platzhalter stuff should work in the background.

**Links/References**
* Traefik: https://docs.traefik.io/

**Tasks**

- [x] Add firewall rules to prevent other ports than SSH and HTTPS
- [x] Add [Traefik](https://docs.traefik.io/) to forward incoming traffic to Platzhalter
- [x] Configure Traefik for Let's Encrypt (redirect HTTP to HTTPS)
- [x] Configure docker-compose or whatever is necessary to do this

**Additional Context**
The firewall setup should be done in `server-install.sh`.
