### ISSUE TITLE
Setup GitHub issues

### ISSUE THREAD

**Issue by Narigo** [compose-us-research/noqueue#3]
Right now, the repository is not really inviting for new people. To make others be able to join the fun, we should add issue templates, a code of conduct, contributing guidelines and label open issues we still need to address.

- [x] Add labels
- [ ] Setup issue templates (Bug, Feature)
- [ ] Add code of conduct
- [ ] Add contributing guidelines

---
Proposal for issue templates:
**BUG_REPORT.md**
```
---
name: Bug report
about: Create a report of the issue you've encountered.
---

**Please check each**

- [ ] Added label "bug"

**Steps to reproduce**

1. Go to ...
2. Click on ...
3. Scroll down to ...
4. See error

**What is the current bug behavior?**
(What actually happens)

**What is the expected correct behavior?**
(What you should see instead)

**Relevant logs and/or screenshots**
(Paste any relevant logs - please use code blocks (` ```...``` `) to format console output, logs, and code as it's very hard to read otherwise.)

**Possible fixes**
(If you can, link to the line of code that might be responsible for the problem)
```

**FEATURE_REQUEST.md**
```
---
name: Feature Request
about: Request a new feature
---
**Description**
(Please give a description of the new feature)

**Links/References**
(Add any designs, screenshots or links that helpful to implement the feature)

**Tasks**

- [ ] Add ...
- [ ] Document ...

**Additional Context**
(Add any additional context relevant to this feature)
```
