### ISSUE TITLE
Make it possible to register multiple time ranges as shop owner

### ISSUE THREAD

**Issue by Narigo** [compose-us-research/noqueue#4]
**Description**
A shop owner needs to be able to set multiple time ranges when customers can enter / book their tickets for the shop.

**Links/References**
![image](https://user-images.githubusercontent.com/1767865/80867790-3fb48680-8c96-11ea-9b87-8c226bf32612.png)

**Tasks**

- [x] Decide on where to put the amount of customers - in the time range or in the shop registration -> **It should stay in the time range for flexibility**
- [ ] Show all time ranges that are available from the shop
- [ ] Add "Zeitraum hinzufügen" button to add more time ranges
- [ ] Add submit button to put all time ranges to the server
- [ ] Make sure "Wählbarer Zeitraum" cannot be longer than the amount of minutes in "Uhrzeit von/bis"

**Additional Context**
There is an open question / discussion whether we should add the amount of customers into the time ranges or into the shop itself. Putting it into the time ranges would be more flexible, but in the shop itself, is easier to manage.

**Comment by Narigo** [comment]
@steffi501 what do you think is best: Amount of customers on the shop or on the time ranges?

**Comment by Narigo** [comment]
Oh and how is deleting a time range going to work? :)

**Comment by steffi501** [comment]
Look look - what do you think about this solution? 

![Timeslots-edit](https://user-images.githubusercontent.com/5849330/80921557-71514e80-8d77-11ea-83f9-0a864237ea8f.jpg)

I think the amount of customers on the time ranges is more flexible, but also more complicated to explain to the user. Nevertheless, I prefer it on the time ranges. Maybe we have to add a small helper text on this field.

**Comment by Narigo** [comment]
Nice!

So the days should be checkboxes instead of a "radio" selection, right?
Shall we make "Zeitraum X" into "Vormittags" etc...? I'm a bit unsure how to implement the computed Mo-Fr for permutations like "Mo, Mi, Fr, Sa" and keep it short enough...

I would prefer to have the delete button not directly on the expander button - I would put it into the expanded area. I think it's a bit too easy to loose things, what do you think?

Shall the whole thing be an accordion or can we expand multiple time ranges?

**Comment by steffi501** [comment]
Look, what do you think about that flow? Hope it's a bit clearer now :) (in Figma it's clickable, too)

![Zeitslots hinterlegen - Zeitraum 1 Open](https://user-images.githubusercontent.com/5849330/80926135-8937cb00-8d95-11ea-9b6e-12958020ab5d.jpg)
![Zeitslots hinterlegen - Zeitraum 2 Open](https://user-images.githubusercontent.com/5849330/80926136-89d06180-8d95-11ea-9b30-e55fd03497c0.jpg)

I think the delete button fits better in the expanded area, yes. Can we add a modal "Are you sure blabla" when clicking the delete button? Or is it complicated to implement? The plan was to implement the time ranges as an accordion, yes. What do you think?

I also thought, we could use Selects instead of the time range slider? Just an idea - less fancy, but maybe good for a more consistent design and better usability on mobile devices... 

![Zeitslots hinterlegen - Select Variation](https://user-images.githubusercontent.com/5849330/80926132-863cda80-8d95-11ea-9016-77db59ec74ed.jpg)
