### ISSUE TITLE
Use X-Forwarded-Proto header to identify the correct protocol for @ids

### ISSUE THREAD

**Issue by Narigo** [compose-us-research/noqueue#45]
**Description**
The backend currently sends out an `http` link for the ids of the shops. If using HTTPS, this resulted in errors, which is why we removed the protocol from the link in the frontend. A better patch for this is to forward the protocol in the [`X-Forwarded-Proto` header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-Proto) to make sure the correct URLs are generated. This can be done by Traefik.

**Links/References**
- [`X-Forwarded-Proto` header on MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-Proto)
- [Traefik documentation for forwarding headers](https://docs.traefik.io/middlewares/headers/#sslproxyheaders)

**Tasks**

- [x] Configure traefik to add the X-Forward-Proto header
- [x] Remove the `idToLink` function
- [ ] Test if everything works as expected

**Additional Context**
It was quite a fast hotfix with the removal of the protocol in the ID - otherwise the beta couldn't be used at all. It should be fixed properly though as time permits.
