### ISSUE TITLE
Manage versions of the database

### ISSUE THREAD

**Issue by Narigo** [compose-us-research/noqueue#48]
**Description**
The current tables approach works for an initial setup with creation on initialization. If we need to modify tables or add information to them, we need some way to tell if we need to update them.

**Links/References**
(Add any designs, screenshots or links that helpful to implement the feature)

**Tasks**

- [ ] Create an initial snapshot of the database tables
- [ ] Create a table with a counter of the currently used version
- [ ] Add setup file(s) that increment the version with the appropriate changes and change the version
- [ ] Make the initialization phase of the server aware of having to update the database if necessary

**Additional Context**
Ruby on Rails has a nice system for doing this with its migrations. It would suffice for us if we had a simple "run this script on version change from A to B" and run these change scripts in the correct order.
