### ISSUE TITLE
Create user-flow for user management

### ISSUE THREAD

**Issue by Narigo** [compose-us-research/noqueue#50]
**Description**
A user needs to login to register or update a shop. Right now, the user management is implemented in the backend, but the frontend is still missing.

**Links/References**
Related to #7 

**Tasks**

- [ ] Add a login frontend when user wants to register / update a shop
- [ ] Save login token in frontend
- [ ] Send login token with each request to the backend

**Additional Context**
There is a [pull request](https://github.com/compose-us-research/noqueue/pulls/13) for the backend already
