### ISSUE TITLE
Use smaller docker image

### ISSUE THREAD

**Issue by Narigo** [compose-us-research/noqueue#70]
**Description**
`node:12` is used as the base image of our docker. The `node:12-slim` or something could be used to make it smaller.

**Links/References**
- [Available node base docker images](https://hub.docker.com/_/node/)

**Tasks**

- [x] Use `node:12-slim` as base image in the `Dockerfile`
- [x] Copy `package.json` / `package-lock.json` / `yarn.lock` before copying everything else to make Docker build faster
- [x] Get rid of `devDependencies` in resulting image through one of these alternatives:
  - use `docker build --squash` - needs configuration for experimental features
  - use https://github.com/goldmann/docker-squash - needs installation
  - use multi-staged build
- [x] Check that everything still works and install missing dependencies if something is missing

**Additional Context**
Uploading when updating the server takes a looooong time from the home connection of @Narigo. It might be possible to cut this time by making the docker images a lot smaller.

**Comment by Narigo** [comment]
Used multi-staged build now to get rid of dev dependencies and frontend node_modules as the frontend builds into a bundled static page - frontend `build` directory is copied over only.
