### ISSUE TITLE
Use Pool instead of Client from postgres module

### ISSUE THREAD

**Issue by Narigo** [compose-us-research/noqueue#77]
**Description**
The backend uses a single `Client` for all queries to the database in a single shop. It could use the `Pool` and work with just a couple of connections for all shops of an instance.

**Links/References**
(Add any designs, screenshots or links that helpful to implement the feature)

**Tasks**

- [ ] Check that each shop still has its own `prefix` "connection"
- [ ] Use the same pool for the real database connection
- [ ] Test that everything still works with multiple connections

**Additional Context**
The current architecture should work for a couple of shops if there are not too many people reserving slots at the same time. Using a `Pool` instead would make it scale better if you decide to host multiple highly frequented shops.
