### ISSUE TITLE
Cancelling a ticket should make the ticket not disappear completely if it was used already.

### ISSUE THREAD

**Issue by Narigo** [compose-us-research/noqueue#81]
**Description**
The current state of cancelling a ticket removes it completely from the user. If the slot already began, the ticket should still be available though.

**Links/References**
- Ticket #22 for the initial implementation of the cancellation
- Ticket #48 to make database changes possible

**Tasks**

- [ ] Make database versions possible #48 
- [ ] Add a nullable `deleted_at` column in table `ticket`
- [ ] Implement the backend change to mark tickets as deleted
- [ ] Implement the backend change to not hand out tickets that are marked as deleted

**Additional Context**
Frontend should work already thanks to #22
