### ISSUE TITLE
Finalize logo and favicon

### ISSUE THREAD

**Issue by Narigo** [compose-us-research/noqueue#89]
**Description**
Add logo and favicon to Figma and mark the relevant one that we should use.

**Links/References**
(Add any designs, screenshots or links that helpful to implement the feature)

**Tasks**

- [ ] Create logo (@steffi501)
- [ ] Create favicon (@steffi501)
- [ ] Mark logo and favicon to use (@steffi501)
- [ ] Export logo and favicon and implement it in the app (@Narigo)
- [ ] Enjoy the logo live (@Wiesusenurmitj)

**Additional Context**
Draw or buy :)
