### ISSUE TITLE
Use days instead of minutes as timeslots

### ISSUE THREAD

**Issue by Narigo** [compose-us-research/noqueue#95]
**Description**
The current implementation only allows timeslots as minutes, not as days. Using days instead of minutes should be an additional feature.

**Links/References**
- Times do not need to be set, only days
- Days could be selected as blacklist or whitelist

**Tasks**

- [ ] Add a migration for the database (#48) to allow setting days
- [ ] Add the possibility to set a blacklist (or whitelist) for the days in the backend
- [ ] Add the possibility to set them in `/owner`
- [ ] Show the availability of the days in `/available` (maybe a general fix for #12 might make sense here)
- [ ] Add a frontend to select the days in a calendar

**Additional Context**
Using days makes more sense in a setting like camping spaces for example.
